const Ziggy = {
  url: 'http:\/\/localhost',
  port: null,
  defaults: {},
  routes: {
    'boost.browser-logs': { uri: '_boost\/browser-logs', methods: ['POST'] },
    login: { uri: 'login', methods: ['GET', 'HEAD'] },
    register: { uri: 'register', methods: ['GET', 'HEAD'] },
    logout: { uri: 'logout', methods: ['POST'] },
    dashboard: { uri: '\/', methods: ['GET', 'HEAD'] },
    'dashboard.index': { uri: 'dashboard', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
    'profile.avatar.update': { uri: 'profile\/avatar', methods: ['PUT'] },
    'profile.password.update': { uri: 'profile\/password', methods: ['PUT'] },
    'notifications.index': { uri: 'notifications', methods: ['GET', 'HEAD'] },
    'notifications.read-all': { uri: 'notifications\/read-all', methods: ['POST'] },
    'notifications.read': {
      uri: 'notifications\/{notification}\/read',
      methods: ['POST'],
      parameters: ['notification'],
    },
    'customers.index': { uri: 'customers', methods: ['GET', 'HEAD'] },
    'customers.create': { uri: 'customers\/create', methods: ['GET', 'HEAD'] },
    'customers.store': { uri: 'customers', methods: ['POST'] },
    'customers.show': {
      uri: 'customers\/{customer}',
      methods: ['GET', 'HEAD'],
      parameters: ['customer'],
      bindings: { customer: 'id' },
    },
    'customers.edit': {
      uri: 'customers\/{customer}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['customer'],
      bindings: { customer: 'id' },
    },
    'customers.update': {
      uri: 'customers\/{customer}',
      methods: ['PUT', 'PATCH'],
      parameters: ['customer'],
      bindings: { customer: 'id' },
    },
    'customers.destroy': {
      uri: 'customers\/{customer}',
      methods: ['DELETE'],
      parameters: ['customer'],
      bindings: { customer: 'id' },
    },
    'customers.import': { uri: 'customers\/import', methods: ['POST'] },
    'projects.index': { uri: 'projects', methods: ['GET', 'HEAD'] },
    'projects.create': { uri: 'projects\/create', methods: ['GET', 'HEAD'] },
    'projects.store': { uri: 'projects', methods: ['POST'] },
    'projects.show': {
      uri: 'projects\/{project}',
      methods: ['GET', 'HEAD'],
      parameters: ['project'],
      bindings: { project: 'id' },
    },
    'projects.edit': {
      uri: 'projects\/{project}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['project'],
      bindings: { project: 'id' },
    },
    'projects.update': {
      uri: 'projects\/{project}',
      methods: ['PUT', 'PATCH'],
      parameters: ['project'],
      bindings: { project: 'id' },
    },
    'projects.destroy': {
      uri: 'projects\/{project}',
      methods: ['DELETE'],
      parameters: ['project'],
      bindings: { project: 'id' },
    },
    'projects.attachments.view': {
      uri: 'projects\/{project}\/attachments\/{attachment}\/view',
      methods: ['GET', 'HEAD'],
      parameters: ['project', 'attachment'],
      bindings: { project: 'id', attachment: 'id' },
    },
    'projects.attachments.download': {
      uri: 'projects\/{project}\/attachments\/{attachment}\/download',
      methods: ['GET', 'HEAD'],
      parameters: ['project', 'attachment'],
      bindings: { project: 'id', attachment: 'id' },
    },
    'drawing-requests.index': { uri: 'drawing-requests', methods: ['GET', 'HEAD'] },
    'drawing-requests.create': { uri: 'drawing-requests\/create', methods: ['GET', 'HEAD'] },
    'drawing-requests.store': { uri: 'drawing-requests', methods: ['POST'] },
    'drawing-requests.show': {
      uri: 'drawing-requests\/{drawing_request}',
      methods: ['GET', 'HEAD'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.edit': {
      uri: 'drawing-requests\/{drawing_request}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.update': {
      uri: 'drawing-requests\/{drawing_request}',
      methods: ['PUT', 'PATCH'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.destroy': {
      uri: 'drawing-requests\/{drawing_request}',
      methods: ['DELETE'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.assign': {
      uri: 'drawing-requests\/{drawing_request}\/assign',
      methods: ['POST'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.mark-ready': {
      uri: 'drawing-requests\/{drawing_request}\/mark-ready',
      methods: ['POST'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.cancel': {
      uri: 'drawing-requests\/{drawing_request}\/cancel',
      methods: ['POST'],
      parameters: ['drawing_request'],
    },
    'drawing-requests.hold': {
      uri: 'drawing-requests\/{drawing_request}\/hold',
      methods: ['POST'],
      parameters: ['drawing_request'],
    },
    'submittals.index': { uri: 'submittals', methods: ['GET', 'HEAD'] },
    'submittals.show': {
      uri: 'submittals\/{submittal}',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.destroy': {
      uri: 'submittals\/{submittal}',
      methods: ['DELETE'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.create-from-request': {
      uri: 'submittals\/from-request\/{drawing_request}',
      methods: ['POST'],
      parameters: ['drawing_request'],
    },
    'submittals.submit': {
      uri: 'submittals\/{submittal}\/submit',
      methods: ['POST'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.process-approval': {
      uri: 'submittals\/{submittal}\/process-approval',
      methods: ['POST'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.create-revision': {
      uri: 'submittals\/{submittal}\/create-revision',
      methods: ['POST'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.files.view': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/view',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.download': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/download',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.markups.index': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.markups.store': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups',
      methods: ['POST'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.markups.import': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups\/import',
      methods: ['POST'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.markups.update': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups\/{markup}',
      methods: ['PUT'],
      parameters: ['submittal', 'submittalFile', 'markup'],
      bindings: { submittal: 'id', submittalFile: 'id', markup: 'id' },
    },
    'submittals.files.markups.destroy': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups\/{markup}',
      methods: ['DELETE'],
      parameters: ['submittal', 'submittalFile', 'markup'],
      bindings: { submittal: 'id', submittalFile: 'id', markup: 'id' },
    },
    'submittals.files.page-scales.index': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/page-scales',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.page-scales.upsert': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/page-scales\/{pageNumber}',
      methods: ['PUT'],
      parameters: ['submittal', 'submittalFile', 'pageNumber'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.page-scales.destroy': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/page-scales\/{pageNumber}',
      methods: ['DELETE'],
      parameters: ['submittal', 'submittalFile', 'pageNumber'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.files.markups.export': {
      uri: 'submittals\/{submittal}\/files\/{submittalFile}\/markups\/export',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal', 'submittalFile'],
      bindings: { submittal: 'id', submittalFile: 'id' },
    },
    'submittals.notes.index': {
      uri: 'submittals\/{submittal}\/notes',
      methods: ['GET', 'HEAD'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'submittals.notes.store': {
      uri: 'submittals\/{submittal}\/notes',
      methods: ['POST'],
      parameters: ['submittal'],
      bindings: { submittal: 'id' },
    },
    'fab-queue.index': { uri: 'fab-queue', methods: ['GET', 'HEAD'] },
    'fab-queue.show': {
      uri: 'fab-queue\/{fab_queue}',
      methods: ['GET', 'HEAD'],
      parameters: ['fab_queue'],
    },
    'fab-queue.assign': {
      uri: 'fab-queue\/{fab_queue}\/assign',
      methods: ['POST'],
      parameters: ['fab_queue'],
    },
    'fab-queue.complete': {
      uri: 'fab-queue\/{fab_queue}\/complete',
      methods: ['POST'],
      parameters: ['fab_queue'],
    },
    'fab-queue.update-notes': {
      uri: 'fab-queue\/{fab_queue}\/notes',
      methods: ['PUT'],
      parameters: ['fab_queue'],
    },
    'admin.users.index': { uri: 'admin\/users', methods: ['GET', 'HEAD'] },
    'admin.users.store': { uri: 'admin\/users', methods: ['POST'] },
    'admin.users.update': {
      uri: 'admin\/users\/{user}',
      methods: ['PUT'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'admin.users.destroy': {
      uri: 'admin\/users\/{user}',
      methods: ['DELETE'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'admin.backups.index': { uri: 'admin\/backups', methods: ['GET', 'HEAD'] },
    'admin.backups.store': { uri: 'admin\/backups', methods: ['POST'] },
    'admin.backups.restore': { uri: 'admin\/backups\/restore', methods: ['POST'] },
    'admin.backups.download': {
      uri: 'admin\/backups\/{fileName}',
      methods: ['GET', 'HEAD'],
      parameters: ['fileName'],
    },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
